### ISSUE TITLE
Expose Grafana as HTTPS

### ISSUE THREAD

**Issue by efy** [dokku/dokku-graphite#18]
Is it possible to expose Grafana on https using this plugin?

**Comment by nemtsov** [comment]
@efy I'm doing this manually via `certbot`, btw [using these instructions](https://certbot.eff.org/lets-encrypt/ubuntuartful-nginx). It was very straight-forward to set up and install.

In cause you go down that route, the only issue I've had was there was a conflict with `server_names_hash_bucket_size` (error: `nginx: [emerg] "server_names_hash_bucket_size" directive is duplicate in /etc/nginx/conf.d/server_names_hash_bucket_size.conf:1`) which prevented nginx from restarting. `mv /etc/nginx/conf.d/server_names_hash_bucket_size.conf /tmp/server_names_hash_bucket_size.conf` is a workaround for that.

**Comment by josegonzalez** [comment]
After thinking about this more, the correct way to do this is to use a [service-proxy](https://github.com/dokku/service-proxy) (tested on 0.25.3):

```shell
# In this example, a graphite service named lollipop will be exposed under the app service-proxy
dokku apps:create service-proxy
dokku config:set service-proxy SERVICE_NAME=lollipop SERVICE_TYPE=graphite SERVICE_PORT=80
dokku graphite:create lollipop
dokku graphite:link lollipop service-proxy
dokku git:from-image service-proxy dokku/service-proxy:latest
```

You can then treat the service-proxy app as any other, including adding an ssl cert (even via letsencrypt). Hope this helps.
